spring:
  application:
    name: user-service
  jpa:
    properties:
      hibernate:
        generate_statistics: true
  flyway:
    enabled: true
    schemas: public
    locations: classpath:/db/migration
    baseline-on-migrate: true
  cloud:
    aws:
      sqs:
        vehicle_listener: vehicle-listener
      sns:
        topic_user_test: topic-user-test
server:
  port: 9923